sudo: false
dist: xenial

language: python
python:
    - "3.6"
    - "3.7-dev"
    - "3.8-dev"

matrix:
  fast_finish: true
  allow_failures:
    - python: "3.8-dev"

install:
  - travis_retry pip install -U tox-travis
script:
  - tox
after_success:
  - tox -e codecov
