__name__ = 'mountapi'
__url__ = 'https://mountapi.org'
__version__ = 'unreleased'
__author__ = 'Piotr Szpetkowski'
__author_email__ = 'piotr.szpetkowski@pyquest.space'
__license__ = 'MIT'
__copyright__ = 'Copyright 2018 Piotr Szpetkowski'
